services:
  db:
    image: postgres:16
    container_name: online-shop-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wildfly_db
      POSTGRES_USER: wildfly_user
      POSTGRES_PASSWORD: password123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wildfly_user -d wildfly_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - online-shop-app

  pgadmin:
    image: dpage/pgadmin4
    container_name: online-shop-pgadmin4
    restart: always
    ports:
      - "8855:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - online-shop-app

  wildfly:
    container_name: online-shop-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8080"      # Applikation
      - "9090:9990"      # Management Konsole
    environment:
      DB_HOST: db
      DB_NAME: wildfly_db
      DB_USER: wildfly_user
      DB_PASS: password123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - online-shop-app

volumes:
  local_pgdata:
  pgadmin-data:
networks:
  online-shop-app: